apiVersion: v1
kind: Secret
metadata:
  name: ordersaga-secret
type: Opaque
data:
  spring.datasource.url: {{ printf "jdbc:postgresql://%s:%s/%s?user=%s&password=%s" (include "postgresql.fullname" .) .Values.common.postgresql.service.port .Values.common.postgresql.postgresqlDatabase .Values.common.postgresql.postgresqlUsername .Values.common.postgresql.postgresqlPassword  | b64enc | quote }}
