replicaCount: 1

image:
  tag: 1.0.0

containerPort: 8088

envSecrets:
  spring.datasource.url: notification-secret

env:
  spring.mail.username: egrocery.noreply@gmail.com
  spring.mail.password: egrocery123

service:
  type: NodePort
  port: 9000
