ingress:
  annotations: {
    kubernetes.io/ingress.class: nginx,
    nginx.ingress.kubernetes.io/rewrite-target: /
  }
  host: "e-grocery"
  path: /
  backend:
    serviceName: gateway-service
    servicePort: 9000
