apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: common
version: 0.1.0
dependencies:
  - name: postgresql
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
