apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "ingress"
  labels:
    app: ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: "gateway-service"
              servicePort: 9000
