server:
  port: 8080

spring:
  application.name: gateway
  thymeleaf.cache: false

zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes.products.url: http://localhost:8081
  routes.orders.url: http://localhost:8082
  routes.payments.url: http://localhost:8083
  routes.ordersaga.url: http://localhost:8084
  routes.shipments.url: http://localhost:8085
  routes.profiles.url: http://localhost:8086
  routes.search.url: http://localhost:8087

keycloak:
  auth-server-url: http://localhost:8090/auth
  realm: E-GROCERY
  resource: gateway
  public-client: true
  principal-attribute: preferred_username

ribbon:
  eureka:
    enabled: false

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

      group.readiness.include: '*'
      group.readiness.show-details: always

      group.liveness.include: '*'
      group.liveness.show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

#logging.level.org.springframework.cloud.netflix: trace
