apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Chart.Name "service" }}
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  type: {{ .Values.service.type }}
  ports:
    - name: gateway-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web