apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: profile
spec:
  selector:
    app: profile
  type: {{ .Values.service.type }}
  ports:
    - name: profile-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8086
