apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: search
spec:
  selector:
    app: search
  type: {{ .Values.service.type }}
  ports:
    - name: search-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
