apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Chart.Name "secret" }}
type: Opaque
data:
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.keycloak.admin.username | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | b64enc | quote }}
  KEYCLOAK_DB_USERNAME: {{ .Values.keycloak.db.username | b64enc | quote }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.keycloak.db.password | b64enc | quote }}
