apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Chart.Name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      nodePort: 30080
